export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_DRIVER_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_DRIVER_SUCCESS';
export const USER_ROLE_SUCCESS = 'USER_ROLE_SUCCESS';

export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAIL = 'FETCH_USER_DATA_FAIL';
export const ADD_DRIVER_LICENSE_SUCCESS = 'FETCH_DRIVER_LICENSE_SUCCESS';
export const REMOVE_USER_DATA_SUCCESS = 'REMOVE_USER_DATA_SUCCESS';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';

export const FETCH_DRIVER_VEHICLES_START = 'FETCH_DRIVER_VEHICLES_START';
export const FETCH_DRIVER_VEHICLES_SUCCESS = 'FETCH_DRIVER_VEHICLES_SUCCESS';
export const FETCH_DRIVER_VEHICLES_FAIL = 'FETCH_DRIVER_VEHICLES_FAIL';
export const DELETE_DRIVER_VEHICLE_SUCCESS = 'DELETE_DRIVER_VEHICLE_SUCCESS';
export const ADD_DRIVER_VEHICLE_SUCCESS = 'ADD_DRIVER_VEHICLE_SUCCESS';
export const FETCH_VEHICLE_SUCCESS = 'FETCH_VEHICLE_SUCCESS';

export const FETCH_RESERVATIONS_START = 'FETCH_RESERVATIONS_START';
export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_FAIL = 'FETCH_RESERVATIONS_FAIL';
export const ADD_RESERVATION_SUCCESS = 'ADD_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const CANCEL_RESERVATION_SUCCESS = 'CANCEL_RESERVATION_SUCCESS';
export const UPDATE_RESERVATION_PAYMENT_SUCCESS = 'UPDATE_RESERVATION_PAYMENT_SUCCESS';

export const FETCH_AREA_START = 'FETCH_AREA_START';
export const FETCH_AREAS_SUCCESS = 'FETCH_AREAS_SUCCESS';
export const FETCH_AREA_SUCCESS = 'FETCH_AREA_SUCCESS';
export const FETCH_AREA_FAIL = 'FETCH_AREA_FAIL';
export const CLOSE_AREA_SELECTION = 'CLOSE_AREA_SELECTION';

export const UPDATE_ERROR_SUCCESS = 'UPDATE_ERROR_SUCCESS';
