export const AUTH_DRIVER_START = 'AUTH_DRIVER_START';
export const AUTH_DRIVER_SUCCESS = 'AUTH_DRIVER_SUCCESS';
export const AUTH_DRIVER_FAIL = 'AUTH_DRIVER_FAIL';
export const AUTH_DRIVER_LOGOUT = 'AUTH_DRIVER_LOGOUT';

export const FETCH_DRIVER_DATA_START = 'FETCH_DRIVER_DATA_START';
export const FETCH_DRIVER_DATA_SUCCESS = 'FETCH_DRIVER_DATA_SUCCESS';
export const FETCH_DRIVER_DATA_FAIL = 'FETCH_DRIVER_DATA_FAIL';
export const ADD_DRIVER_LICENSE_SUCCESS = 'FETCH_DRIVER_LICENSE_SUCCESS';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';

export const FETCH_DRIVER_VEHICLES_START = 'FETCH_DRIVER_VEHICLES_START';
export const FETCH_DRIVER_VEHICLES_SUCCESS = 'FETCH_DRIVER_VEHICLES_SUCCESS';
export const FETCH_DRIVER_VEHICLES_FAIL = 'FETCH_DRIVER_VEHICLES_FAIL';
export const DELETE_DRIVER_VEHICLE_SUCCESS = 'DELETE_DRIVER_VEHICLE_SUCCESS';
export const ADD_DRIVER_VEHICLE_SUCCESS = 'ADD_DRIVER_VEHICLE_SUCCESS';
