export const AUTH_DRIVER_START = 'AUTH_DRIVER_START';
export const AUTH_DRIVER_SUCCESS = 'AUTH_DRIVER_SUCCESS';
export const AUTH_DRIVER_FAIL = 'AUTH_DRIVER_FAIL';
export const AUTH_DRIVER_LOGOUT = 'AUTH_DRIVER_LOGOUT';
export const AUTH_REGISTER_DRIVER_SUCCESS = 'AUTH_REGISTER_DRIVER_SUCCESS';

export const FETCH_DRIVER_DATA_START = 'FETCH_DRIVER_DATA_START';
export const FETCH_DRIVER_DATA_SUCCESS = 'FETCH_DRIVER_DATA_SUCCESS';
export const FETCH_DRIVER_DATA_FAIL = 'FETCH_DRIVER_DATA_FAIL';
export const ADD_DRIVER_LICENSE_SUCCESS = 'FETCH_DRIVER_LICENSE_SUCCESS';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';

export const FETCH_DRIVER_VEHICLES_START = 'FETCH_DRIVER_VEHICLES_START';
export const FETCH_DRIVER_VEHICLES_SUCCESS = 'FETCH_DRIVER_VEHICLES_SUCCESS';
export const FETCH_DRIVER_VEHICLES_FAIL = 'FETCH_DRIVER_VEHICLES_FAIL';
export const DELETE_DRIVER_VEHICLE_SUCCESS = 'DELETE_DRIVER_VEHICLE_SUCCESS';
export const ADD_DRIVER_VEHICLE_SUCCESS = 'ADD_DRIVER_VEHICLE_SUCCESS';

export const FETCH_RESERVATIONS_START = 'FETCH_RESERVATIONS_START';
export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_FAIL = 'FETCH_RESERVATIONS_FAIL';
export const ADD_RESERVATION_SUCCESS = 'ADD_RESERVATION_SUCCESS';
export const FETCH_VEHICLE_RESERVATIONS_SUCCESS = 'FETCH_VEHICLE_RESERVATIONS_SUCCESS';
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const CANCEL_RESERVATION_SUCCESS = 'CANCEL_RESERVATION_SUCCESS';

export const FETCH_AREA_START = 'FETCH_AREA_START';
export const FETCH_AREA_SUCCESS = 'FETCH_AREA_SUCCESS';
export const FETCH_AREA_FAIL = 'FETCH_AREA_FAIL';
export const CLOSE_AREA_SELECTION = 'CLOSE_AREA_SELECTION';
